[modules]
"slug.db.sqlite" = { source = "modules/sqlite.slug" }
"slug.db.sqlite.statement" = { source = "modules/statement.slug" }
"slug.db.sqlite.transaction" = { source = "modules/transaction.slug" }

[native]
source = "native/source"
abi = "slug-ffi-prototype/0.12"

[native.libraries]
"macos-aarch64" = "native/macos-aarch64/libslug_db_sqlite.dylib"
"macos-x86_64" = "native/macos-x86_64/libslug_db_sqlite.dylib"
"linux-x86_64" = "native/linux-x86_64/libslug_db_sqlite.so"
"windows-x86_64" = "native/windows-x86_64/slug_db_sqlite.dll"
