[workspace]
members = ["crates/slug-vm", "crates/slug-server", "crates/slug-repl"]
resolver = "3"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = "symbols"
panic = "abort"

[workspace.lints.rust]
unsafe_code = "deny"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
