[modules]
"slug.io.fs" = { source = "modules/fs.slug", native = true }

[native]
source = "native/source"
abi = "slug-ffi-prototype/0.7"

[native.libraries]
"macos-aarch64" = "native/macos-aarch64/libslug_io_fs.dylib"
"macos-x86_64" = "native/macos-x86_64/libslug_io_fs.dylib"
"linux-x86_64" = "native/linux-x86_64/libslug_io_fs.so"
