use std::{cell::RefCell, collections::BTreeMap, fmt, rc::Rc};

use serde::Deserialize;
use serde_json::{Value, json};

use crate::{
    NativeArity, NativeCall, NativeDescriptorError, NativeFunction, NativeModule, NativeOwnedValue,
    NativeStatus, Value as SlugValue, Vm,
    source::{InteractiveCompilerState, compile_interactive},
    vm::InteractiveEnvironment,
};
#[cfg(feature = "concurrency")]
use crate::{VmProgress, source::InteractiveCompilation, vm::InteractiveTask};

use super::{Diagnostic, Event, PROTOCOL_VERSION, Request, Response};

/// The protocol event stream used for host or program output.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum OutputStream {
    Stdout,
    Stderr,
}

impl OutputStream {
    const fn event_name(self) -> &'static str {
        match self {
            Self::Stdout => "stdout",
            Self::Stderr => "stderr",
        }
    }
}

/// Failure to attribute host output to a live interactive session.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum OutputError {
    UnknownSession(String),
}

impl fmt::Display for OutputError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::UnknownSession(session) => write!(formatter, "unknown session `{session}`"),
        }
    }
}

impl std::error::Error for OutputError {}

/// In-process owner of interactive-session protocol lifecycle.
pub struct Server {
    vm: Vm,
    initialized: bool,
    sessions: BTreeMap<String, Session>,
    next_session: u64,
    output: Rc<RefCell<OutputSink>>,
}

struct Session {
    compiler: InteractiveCompilerState,
    runtime: InteractiveEnvironment,
    #[cfg(feature = "concurrency")]
    execution: SessionExecution,
}

#[cfg(feature = "concurrency")]
enum SessionExecution {
    Idle,
    Active {
        task: InteractiveTask,
        compilation: InteractiveCompilation,
    },
    Stalled {
        task: InteractiveTask,
        compilation: InteractiveCompilation,
    },
}

#[derive(Default)]
struct OutputSink {
    active_session: Option<String>,
    events: Vec<Event>,
}

impl OutputSink {
    fn begin(&mut self, session: String) {
        self.active_session = Some(session);
    }

    fn end(&mut self) {
        self.active_session = None;
    }

    fn write_active(&mut self, stream: OutputStream, data: String) -> bool {
        let Some(session) = &self.active_session else {
            return false;
        };
        self.write(session.clone(), stream, data);
        true
    }

    fn write(&mut self, session: String, stream: OutputStream, data: String) {
        self.events.push(Event {
            session,
            event: stream.event_name().into(),
            data: Value::String(data),
        });
    }
}

impl Server {
    /// Creates a server around the shared VM that future session execution will use.
    #[must_use]
    pub fn new(vm: Vm) -> Self {
        Self {
            vm,
            initialized: false,
            sessions: BTreeMap::new(),
            next_session: 0,
            output: Rc::new(RefCell::new(OutputSink::default())),
        }
    }

    /// Returns the shared embedded VM without starting session execution.
    #[must_use]
    pub fn vm(&self) -> &Vm {
        &self.vm
    }

    /// Registers a shared host binding visible to every session on its next submission.
    ///
    /// # Errors
    ///
    /// Returns a descriptor error when the binding conflicts with an existing host binding.
    pub fn define_host_native(
        &mut self,
        function: NativeFunction,
    ) -> Result<(), NativeDescriptorError> {
        self.vm.define_native(function)
    }

    /// Drains output generated by completed protocol operations.
    #[must_use]
    pub fn take_events(&mut self) -> Vec<Event> {
        std::mem::take(&mut self.output.borrow_mut().events)
    }

    /// Queues host or background-runtime output for a live session.
    ///
    /// The embedding host must supply the session explicitly. Events queued
    /// outside a `submit` are delivered the next time the host drains
    /// [`Self::take_events`]; output is never written directly to protocol
    /// stdout.
    ///
    /// # Errors
    ///
    /// Returns [`OutputError::UnknownSession`] after the session is closed or
    /// when its identifier is not known to this server.
    pub fn emit_output(
        &mut self,
        session: &str,
        stream: OutputStream,
        data: impl Into<String>,
    ) -> Result<(), OutputError> {
        if !self.sessions.contains_key(session) {
            return Err(OutputError::UnknownSession(session.into()));
        }
        self.output
            .borrow_mut()
            .write(session.into(), stream, data.into());
        Ok(())
    }

    /// Handles one decoded protocol request.
    #[must_use]
    pub fn handle(&mut self, request: Request) -> Response {
        match request.method.as_str() {
            "initialize" => self.initialize(request),
            "session.open" => self.open(request),
            "session.close" => self.close(request),
            "submit" => self.submit(request),
            "session.poll" => self.poll(request),
            method => Response::failure(
                Some(request.id),
                request.session,
                Diagnostic::protocol("unknown_method", format!("unknown method `{method}`")),
            ),
        }
    }

    /// Decodes and handles one NDJSON request line without terminating the server.
    #[must_use]
    pub fn handle_line(&mut self, line: &str) -> Response {
        match serde_json::from_str(line) {
            Ok(request) => self.handle(request),
            Err(error) => Response::failure(
                None,
                None,
                Diagnostic::protocol("malformed_json", format!("invalid request JSON: {error}")),
            ),
        }
    }

    fn initialize(&mut self, request: Request) -> Response {
        let params = match required_params::<InitializeParams>(&request, "initialize") {
            Ok(params) => params,
            Err(error) => return Response::failure(Some(request.id), None, *error),
        };
        if request.session.is_some() {
            return Response::failure(
                Some(request.id),
                request.session,
                Diagnostic::protocol("invalid_request", "`initialize` must not include a session"),
            );
        }
        if params.protocol != PROTOCOL_VERSION {
            return Response::failure(
                Some(request.id),
                None,
                Diagnostic::protocol(
                    "unsupported_protocol",
                    format!(
                        "protocol {} is unsupported; expected {PROTOCOL_VERSION}",
                        params.protocol
                    ),
                ),
            );
        }
        self.initialized = true;
        Response::success(
            request.id,
            None,
            json!({
                "protocol": PROTOCOL_VERSION,
                "capabilities": { "sessions": true }
            }),
        )
    }

    fn open(&mut self, request: Request) -> Response {
        if let Some(response) = self.require_initialized(&request) {
            return response;
        }
        if request.session.is_some() || request.params.is_some() {
            return Response::failure(
                Some(request.id),
                request.session,
                Diagnostic::protocol(
                    "invalid_request",
                    "`session.open` must not include a session or params",
                ),
            );
        }
        self.next_session += 1;
        let session = format!("s{}", self.next_session);
        self.sessions.insert(
            session.clone(),
            Session {
                compiler: InteractiveCompilerState::default(),
                runtime: self.vm.interactive_environment(),
                #[cfg(feature = "concurrency")]
                execution: SessionExecution::Idle,
            },
        );
        Response::success(request.id, None, json!({ "session": session }))
    }

    fn close(&mut self, request: Request) -> Response {
        if let Some(response) = self.require_initialized(&request) {
            return response;
        }
        if request.params.is_some() {
            return Response::failure(
                Some(request.id),
                request.session,
                Diagnostic::protocol("invalid_request", "`session.close` does not accept params"),
            );
        }
        let Some(session) = request.session else {
            return Response::failure(
                Some(request.id),
                None,
                Diagnostic::protocol("missing_session", "`session.close` requires a session"),
            );
        };
        #[cfg(feature = "concurrency")]
        if let Some(task) = self.session_task(&session) {
            self.vm.cancel_interactive_task(&task);
        }
        if self.sessions.remove(&session).is_none() {
            return Response::failure(
                Some(request.id),
                Some(session.clone()),
                Diagnostic::protocol("unknown_session", format!("unknown session `{session}`")),
            );
        }
        Response::success(request.id, Some(session), Value::Null)
    }

    fn submit(&mut self, request: Request) -> Response {
        if let Some(response) = self.require_initialized(&request) {
            return response;
        }
        let params = match required_params::<SubmitParams>(&request, "submit") {
            Ok(params) => params,
            Err(error) => return Response::failure(Some(request.id), request.session, *error),
        };
        let Some(session) = request.session else {
            return Response::failure(
                Some(request.id),
                None,
                Diagnostic::protocol("missing_session", "`submit` requires a session"),
            );
        };
        let Some(existing) = self.sessions.get(&session) else {
            return Response::failure(
                Some(request.id),
                Some(session.clone()),
                Diagnostic::protocol("unknown_session", format!("unknown session `{session}`")),
            );
        };
        #[cfg(feature = "concurrency")]
        if !matches!(existing.execution, SessionExecution::Idle) {
            return Response::failure(
                Some(request.id),
                Some(session),
                Diagnostic::protocol(
                    "submission_active",
                    "poll the active submission before submitting more source",
                ),
            );
        }
        let path = format!("<interactive:{session}>");
        let compilation = match compile_interactive(&path, &params.source, &existing.compiler) {
            Ok(compilation) => compilation,
            Err(error) => {
                return Response::failure(
                    Some(request.id),
                    Some(session),
                    Diagnostic::from_source(&error),
                );
            }
        };
        #[cfg(feature = "concurrency")]
        {
            let task = {
                let (vm, sessions) = (&mut self.vm, &mut self.sessions);
                let active = sessions
                    .get_mut(&session)
                    .expect("validated session remains available during submission");
                match vm.start_named_interactive_task(
                    &compilation.program,
                    "main",
                    &mut active.runtime,
                ) {
                    Ok(task) => task,
                    Err(error) => {
                        return Response::failure(
                            Some(request.id),
                            Some(session),
                            Diagnostic::from_runtime(&error),
                        );
                    }
                }
            };
            self.sessions
                .get_mut(&session)
                .expect("validated session remains available during submission")
                .execution = SessionExecution::Active { task, compilation };
            self.drive_session(request.id, session)
        }
        #[cfg(not(feature = "concurrency"))]
        {
            self.output.borrow_mut().begin(session.clone());
            let (vm, sessions) = (&mut self.vm, &mut self.sessions);
            let active = sessions
                .get_mut(&session)
                .expect("validated session remains available during submission");
            let execution =
                vm.run_named_in_environment(&compilation.program, "main", &mut active.runtime);
            self.output.borrow_mut().end();
            match execution {
                Ok(value) => {
                    active.compiler = compilation.state;
                    Response::success(
                        request.id,
                        Some(session),
                        json!({ "value": protocol_value(&value) }),
                    )
                }
                Err(error) => Response::failure(
                    Some(request.id),
                    Some(session),
                    Diagnostic::from_runtime(&error),
                ),
            }
        }
    }

    fn poll(&mut self, request: Request) -> Response {
        if let Some(response) = self.require_initialized(&request) {
            return response;
        }
        if request.params.is_some() {
            return Response::failure(
                Some(request.id),
                request.session,
                Diagnostic::protocol("invalid_request", "`session.poll` does not accept params"),
            );
        }
        let Some(session) = request.session else {
            return Response::failure(
                Some(request.id),
                None,
                Diagnostic::protocol("missing_session", "`session.poll` requires a session"),
            );
        };
        if !self.sessions.contains_key(&session) {
            return Response::failure(
                Some(request.id),
                Some(session.clone()),
                Diagnostic::protocol("unknown_session", format!("unknown session `{session}`")),
            );
        }
        #[cfg(feature = "concurrency")]
        return self.drive_session(request.id, session);
        #[cfg(not(feature = "concurrency"))]
        Response::success(request.id, Some(session), json!({ "state": "idle" }))
    }

    #[cfg(feature = "concurrency")]
    fn session_task(&self, session: &str) -> Option<InteractiveTask> {
        let session = self.sessions.get(session)?;
        match &session.execution {
            SessionExecution::Idle => None,
            SessionExecution::Active { task, .. } | SessionExecution::Stalled { task, .. } => {
                Some(task.clone())
            }
        }
    }

    #[cfg(feature = "concurrency")]
    fn drive_session(&mut self, id: u64, session: String) -> Response {
        let Some(task) = self.session_task(&session) else {
            return Response::success(id, Some(session), json!({ "state": "idle" }));
        };
        self.output.borrow_mut().begin(session.clone());
        let progress = self.vm.run_interactive_task_until_stalled(&task);
        self.output.borrow_mut().end();
        let result = match progress {
            VmProgress::Completed(value) => Some(Ok(value)),
            VmProgress::Failed(error) => Some(Err(error)),
            VmProgress::MadeProgress | VmProgress::Stalled => None,
        };
        let Some(result) = result else {
            let active = self
                .sessions
                .get_mut(&session)
                .expect("active session remains available during its poll");
            let execution = std::mem::replace(&mut active.execution, SessionExecution::Idle);
            active.execution = match execution {
                SessionExecution::Active { task, compilation }
                | SessionExecution::Stalled { task, compilation } => {
                    SessionExecution::Stalled { task, compilation }
                }
                SessionExecution::Idle => SessionExecution::Idle,
            };
            return Response::success(id, Some(session), json!({ "state": "stalled" }));
        };
        let active = self
            .sessions
            .get_mut(&session)
            .expect("active session remains available during its poll");
        let execution = std::mem::replace(&mut active.execution, SessionExecution::Idle);
        let (task, compilation) = match execution {
            SessionExecution::Active { task, compilation }
            | SessionExecution::Stalled { task, compilation } => (task, compilation),
            SessionExecution::Idle => unreachable!("completed task must have session state"),
        };
        task.synchronize_environment(&mut active.runtime);
        self.vm.release_interactive_task(&task);
        match result {
            Ok(value) => {
                Vm::commit_interactive_bindings(&mut active.runtime, &compilation.program);
                active.compiler = compilation.state;
                Response::success(
                    id,
                    Some(session),
                    json!({ "value": protocol_value(&value) }),
                )
            }
            Err(error) => {
                Response::failure(Some(id), Some(session), Diagnostic::from_runtime(&error))
            }
        }
    }

    fn install_output_builtins(&mut self) {
        let module = NativeModule::new("slug.interactive.output", self.output.clone())
            .expect("static interactive output module is valid");
        for (name, callback) in [
            ("print", native_print as NativeCallback),
            ("println", native_println as NativeCallback),
        ] {
            let function = module
                .function(name, NativeArity::Variadic { minimum: 0 }, callback)
                .expect("static interactive output function is valid");
            self.vm
                .define_native(function)
                .expect("interactive output binding is unique");
        }
    }

    fn require_initialized(&self, request: &Request) -> Option<Response> {
        (!self.initialized).then(|| {
            Response::failure(
                Some(request.id),
                request.session.clone(),
                Diagnostic::protocol(
                    "not_initialized",
                    "send `initialize` before session requests",
                ),
            )
        })
    }
}

impl Default for Server {
    fn default() -> Self {
        let mut server = Self::new(Vm::new());
        server.install_output_builtins();
        server
    }
}

type NativeCallback = for<'call> fn(&mut NativeCall<'call>) -> NativeStatus;

fn native_print(call: &mut NativeCall<'_>) -> NativeStatus {
    native_write(call, false)
}

fn native_println(call: &mut NativeCall<'_>) -> NativeStatus {
    native_write(call, true)
}

fn native_write(call: &mut NativeCall<'_>, newline: bool) -> NativeStatus {
    let output = (0..call.argument_count())
        .map(|index| {
            call.argument(index)
                .expect("index comes from the argument count")
                .to_display_string()
        })
        .collect::<Vec<_>>()
        .join(" ");
    let output = if newline {
        format!("{output}\n")
    } else {
        output
    };
    let Some(sink) = call.state::<Rc<RefCell<OutputSink>>>() else {
        return call.raise(crate::NativeError::new(
            "native.output",
            "interactive output sink is unavailable",
        ));
    };
    if !sink.borrow_mut().write_active(OutputStream::Stdout, output) {
        return call.raise(crate::NativeError::new(
            "native.output",
            "interactive output was produced outside a submission",
        ));
    }
    call.return_value(NativeOwnedValue::nil())
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct InitializeParams {
    protocol: u8,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct SubmitParams {
    source: String,
}

fn protocol_value(value: &SlugValue) -> Value {
    match value {
        SlugValue::Nil => Value::Null,
        SlugValue::Bool(value) => Value::Bool(*value),
        SlugValue::Int(value) => json!(value),
        SlugValue::Float(value) if value.is_finite() => json!(value),
        SlugValue::Str(value) => json!(value.as_ref()),
        SlugValue::List(values) => Value::Array(values.iter().map(protocol_value).collect()),
        _ => json!({ "kind": value_kind(value), "display": value.to_string() }),
    }
}

fn value_kind(value: &SlugValue) -> &'static str {
    match value {
        SlugValue::Uninitialized | SlugValue::Binding { .. } => "binding",
        SlugValue::Nil => "nil",
        SlugValue::Bool(_) => "bool",
        SlugValue::Int(_) | SlugValue::Float(_) => "num",
        SlugValue::Str(_) => "str",
        SlugValue::Bytes(_) => "bytes",
        SlugValue::List(_) => "list",
        SlugValue::Map(_) => "map",
        SlugValue::StructSchema(_) => "struct_schema",
        SlugValue::Struct(_) => "struct",
        SlugValue::Enum(_) => "enum",
        SlugValue::Channel(_) => "chan",
        SlugValue::Closure(_)
        | SlugValue::Native(_)
        | SlugValue::DeclaredNative { .. }
        | SlugValue::Builtin(_) => "fn",
        #[cfg(feature = "concurrency")]
        SlugValue::Task(_) => "task",
        SlugValue::NativeResource(_) => "native_resource",
        SlugValue::Overloads(_) => "overloads",
    }
}

fn required_params<T>(request: &Request, method: &str) -> Result<T, Box<Diagnostic>>
where
    T: for<'de> Deserialize<'de>,
{
    let Some(params) = request.params.clone() else {
        return Err(Box::new(Diagnostic::protocol(
            "missing_params",
            format!("`{method}` requires params"),
        )));
    };
    serde_json::from_value(params).map_err(|error| {
        Box::new(Diagnostic::protocol(
            "invalid_params",
            format!("invalid `{method}` params: {error}"),
        ))
    })
}
