[modules]
"slug.math" = { source = "modules/math.slug" }

[native]
source = "native/source"
abi = "slug-ffi-prototype/0.7"

[native.libraries]
"macos-aarch64" = "native/macos-aarch64/libslug_math.dylib"
"macos-x86_64" = "native/macos-x86_64/libslug_math.dylib"
"linux-x86_64" = "native/linux-x86_64/libslug_math.so"
"windows-x86_64" = "native/windows-x86_64/slug_math.dll"
